### ISSUE TITLE
Hubs have no way of knowing whether a message requires `authorization`, `attestation`, or data encryption

### ISSUE THREAD

**Issue by mistermoe** [decentralized-identity/identity-hub#119]
### Problem
The spec does not indicate how an Identity Hub Instance decides whether a message requires `authorization`, `attestation`, or for data to be encrypted. 

### Context
Let's assume the following request is sent to an Identity Hub:
```json
{
    "requestId": "862b44c7-cd7b-4974-8782-b32f470064ef",
    "target": "did:ex:alice",
    "messages": [{
        "descriptor": {
            "objectId": "0f913c1e-cde5-4bbf-956a-80aa481687ad"
            "method": "CollectionsWrite",
            "schema": "https://schema.org/MusicPlaylist",
            "dataFormat": "application/json"
        },
        "data": {...}
    }]
}
```

The message in the request above does not contain `attestation` or `authorization`, nor is `data` encrypted, yet it is a valid message. Further, even if `authorization` was provided, Alice's hub instance currently has no clue whether it should expect `authorization` or not. She should be able to configure what requires any combination of `attestation`, `authorization`, and data encryption based on an individual message's descriptor. 

if the combinatorial suggestion seems like overkill, i'd like to know why and propose that there should be a way to configure what requires `authorization` at the very least.

### Proposal

This proposal **only** focuses on supporting configuration of `authorization`. If there's consensus around supporting configuration of any combination of `authorization`, `attestation`, and encryption, we can extend the proposal.  

We can borrow the concept of DMZ from routers and loosely apply it here.

#### Pseudocode
```javascript
  async processMessage(message) {
    // message validation and other things

    const { descriptor } = message;

    // build DMZ policy out of message's descriptor
    const policy = {};
    for (let field of ['dataFormat', 'method', 'schema']) {
      if (field in descriptor) {
        policy[field] = descriptor[field];
      }
    }

    // check to see if policy is within DMZ
    const isWithinDMZ = !! await this.DMZStore.get(policy);

    // authorization is required if message op is not within DMZ
  }
```
#### Logic
- Build policy out of fields within `message.descriptor`
- Check to see if policy exists in hub's DMZ store
- if it does, no auth is required. 
- Otherwise, expect auth

#### DMZ Policy Data Model
| Field | Data Type | Required (Y/N) |
| -------- | -------- | -------- |
| `dataFormat`     | String     | N     |
| `method`     | String     | N     |
| `schema`     | String     | N     |

### Follow up questions
- Should `DMZ` be it's own interface or live underneath the `Permissions` interface?
    - If as it's own interface, what would that interface look like?
        - would there need to be some hardcoded logic to prevent DMZ checks for DMZ-related messages?
    - if underneath `Permissions` how would that work? Additional Methods?
- Are there any DMZ policies that should be included by default?

**Comment by csuwildcat** [comment]
This kind of thing should be in Permissions, not DMZ in my opinion. Encryption material exchange would be given out at permission issuance time anyway, and the capability would flag that it needs to be encrypted, which it can check on authz eval.

**Comment by decentralgabe** [comment]
Agree that this could be capability based. The policy you've described seems to match with a capability if you have a way to do 'implicit capabilities' - meaning, if someone has a certain authenticated message from a known DID, they auto-get a capability.

The tuple of <schema, dataFormat, method> makes sense for assigning capabilities.

**Comment by mistermoe** [comment]
Closing this out. There was a bunch teased out here that we'll be considering when spec'ing out permissions
