### ISSUE TITLE
Write DMZ proposal

### ISSUE THREAD

**Issue by mistermoe** [decentralized-identity/identity-hub#125]
Context: #119

**Comment by mistermoe** [comment]
# DMZ Proposal

The purpose of DMZ is to determine whether `authorization` is required for inbound messages. This determination is made based on a message's `descriptor`. Specifically, `method` and optionally `schema`

## DMZ Policy Data Model
| Field | Data Type | Required (Y/N) |
| -------- | -------- | ------ |
| `method` | String   | Y      |
| `schema` | String   | N      |



## DMZ Interface

### Methods

#### `DMZPolicyAdd`
```json
{
    "descriptor": {
        "objectId": "some-uuid-v4",
        "method": "DMZPolicyAdd",
        "policy": {
            "method": "THE_METHOD_YOU_WAWNT",
            "schema": "THE_SCHEMA_YOU_WAWNT"
        }
    },
}
```

- A `DMZPolicyAdd` message's descriptor, **MUST** contain the following properties:
    - `objectId` - the id of the policy
    - `method` - durr
    - `policy` - the `policy` property **MUST** be an object that includes the following properties
        - `method` - The method you want to demilitarize
        - `schema` - The schema you want to demilitarize
- A `DMZPolicyAdd` message **MUST** contain `authorization`

**Example Message**:
```json
{
    "descriptor": {
        "objectId": "104932a6-85b3-4fb5-90d2-f46707e2dd8b",
        "method": "DMZPolicyAdd",
        "policy": {
            "method": "ThreadCreate",
            "schema": "https://schema.org/LikeAction"
        }
    },
}
```

This Policy would enable anybody to send Music Playlists to your Identity Hub

#### `DMZPolicyRemove`
```json
{
    "descriptor": {
        "objectId": "some-uuid-v4",
        "method": "DMZPolicyRemove",
    }
}
```

- A `DMZPolicyRemove` message's descriptor, **MUST** contain the following properties:
    - `objectId` - the id of the policy
    - `method` - MUST be the string `DMZPolicyRemove`
- A `DMZPolicyRemove` message **MUST** contain `authorization`
    - `objectId` - the id of the policy you want to remove

### Pseudocode
```javascript
  async processMessage(message) {
    // message validation and other things

    const { descriptor } = message;
    

    // build DMZ policy out of message's descriptor
    const policy = {};
    for (let field of ['method', 'schema']) {
      if (field in descriptor) {
        policy[field] = descriptor[field];
      }
    }

    // check to see if policy is within DMZ
    const isWithinDMZ = !! await this.DMZCache.get(policy);

    // authorization is required if message op is not within DMZ
  }
```


### Logic
- Build policy out of fields within `message.descriptor`
- Check to see if policy exists in hub's DMZ store
- if it does, no auth is required. 
- Otherwise, expect auth

**Comment by mistermoe** [comment]
@csuwildcat,  can you list out the default policies that come to mind?

`{ method: "PermissionsRequest" }`

I believe you also mentioned: `{ method: "CollectionsQuery" }`? Which implies that people can query for anything that's not encrypted or something of the like?

**Comment by csuwildcat** [comment]
The two interfaces you mentioned are the only ones I am aware of that need to be addressable, and items that are encrypted should require subsequent authorization. I think the authz layer is probably the place to determine anything like which objects based on which descriptor values should be open to queries though, don't you think?

**Comment by mistermoe** [comment]
>I think the authz layer is probably the place to determine anything like which objects based on which descriptor values should be open to queries though, don't you think?

Looking for a bit more clarity before i can say for sure:

Let's say someone sends the following message to my hub (omitted request wrapper for brevity):

```json
{
  "descriptor": {
    "method": "CollectionsQuery",
    "schema": "https://schema.org/MusicPlaylist"
  }
}
```

notice that there is no `authorization` present.

Now, let's pass this message through the logic mentioned in the proposal:
- Check DMZ to see if policy exists for message's `method` + `schema` combo
-  If yes, no auth required. run query
- if no, auth required. 
  - evaluate message against capabilities present within `authorization`
  - if message descriptor fits within what's allowed by the presented capabilities, execute op
  - if not, reject message

Now, given that we're saying that `CollectionsQuery` is DMZ'd by default, how exactly are we gating access using authz? `CollectionsQuery` would have to be handled uniquely. Or i suppose we'd go with the suggestion you made in a call awhile back which was to return all non-encrypted data that matches the query.

**Comment by csuwildcat** [comment]
As I understood it, the DMZ interface was just about whether or not an interface/schema policy was present that allowed message traffic through if ANY of that traffic doesn't require authz. In the case of Collections, some queries will require authz, some won't, but what is returned from that interface's invocation is based on eval of the authz and its properties within the scope of the interface's logic. Is this how you were thinking about it?

**Comment by csuwildcat** [comment]
What the DMZ really is, is a shortcut to swatting away messages with no promise of retention and an instant error. If you look at it through the lens of the fact we only have a couple interfaces that are allowed through to stricter eval whether they are authz'd or not. If the feeling is that this the wrong direction for some reason, would the alternative be that we give implementers some function in the Hub instance options that provides for an initial filter they can bounce anything out of for any reason? That would certainly allow them to accept/reject like this. I am not arguing for or against this as an interface, just wondering what you are thinking.

**Comment by agropper** [comment]
I look at this conversation in terms of the burden on the subject of a
request instituted by some other entity.

Can we stipulate that the Hub is purely an agent and chosen by the subject?
If so, then the burden of processing a request falls either on the Hub or
on a delegate of the subject chosen separately from the Hub.

In other words, I think the DMZ characterization is limiting because it
implies that choosing the Hub imposes a DMZ. This seems illogical to the
extent that a Hub service might store or process information across
different contexts (commerce, health, entertainment, employment) while the
processing of requests could be handled by different delegates for each
context (credit card, doctor, social network, team).

**Comment by csuwildcat** [comment]
@agropper this is about a DMZ for swatting messages that should not be allowed into a person/entity's logical Hub/storage without explicitly requiring authorization. This is basic gating that a person/entity will need to setup so you cannot just throw random objects at certain interfaces that do not accept invocations from unauthorized parties.

**Comment by agropper** [comment]
… and how is this different from authorization?

**Comment by mistermoe** [comment]
> As I understood it, the DMZ interface was just about whether or not an interface/schema policy was present that allowed message traffic through if ANY of that traffic doesn't require authz. In the case of Collections, some queries will require authz, some won't, but what is returned from that interface's invocation is based on eval of the authz and its properties within the scope of the interface's logic. Is this how you were thinking about it?

Ah, I'm thinking about DMZ a bit differently. I thinking of DMZ as a way to configure what is publicly accessible. a binary toggle. If a policy is present that matches the interface/schema in an inbound message, then it is demilitarized AKA publicly accessible AKA no auth is required. If no policy is present that matches the interface/schema then auth is defacto required. no policy + no auth would be an immediate short-circuit (aka 401)

For example, if Alice is a blogger, she wants all of her blog posts to be accessible by anyone. to facilitate this, Alice's hub would likely have the following DMZ policy:
```json
{ "method": "CollectionsQuery", "schema": "https://schema.org/BlogPosting" }
```

contrastingly, Alice likely doesn't want any flight reservations to be completely public. Any `CollectionQuery`s for `https://schema.org/FlightReservation` would require a capability to do so.

From this point of view, i think that `{ "method": "CollectionsQuery" }` as a default policy is just far too risky. It leaves too much room for accidentally leaking sensitive data.  I don't think there's any way for someone to confidently know exactly what is and isn't encrypted in their hub. 

I think that any policy for `CollectionsQuery` should require `schema`

**Comment by mistermoe** [comment]
> … and how is this different from authorization?

@agropper, publicly accessible data requires no authorization. A hub needs some way to know what is publicly accessible. What it shouldn't expect authorization for.

**Comment by csuwildcat** [comment]
@mistermoe I disagree with your rendition of a DMZ because I don't think it's practical: are we really going to create a system that requires all users and apps to add endless volumes of DMZ entries just to hit interfaces that can already distinguish what things are allowed to be returned in queries and invocations based on their standard logic in the spec? At that point you'd have to create a mechanism to ask the user to open a DMZ hole just to make your permission actionable, which is really wonky. I think we should limit this to opening queries on Collections and PermissionsRequest, with the former evaluating what it'll return in its own logic.

**Comment by mistermoe** [comment]
>interfaces that can already distinguish what things are allowed to be returned in queries and invocations 

My question from the beginning has been: **how** are these interfaces distinguishing what things are allowed to be returned? That was the main question I asked in #119. Can you point me to where in the spec it says how this is being distinguished? If it is in the spec and i haven't seen it then i wasted our time. I haven't received a clear answer.

> At that point you'd have to create a mechanism to ask the user to open a DMZ hole just to make your permission actionable

Not sure i follow. Can you provide an example to help me understand a bit more clearly?

Generally, i'm a bit confused. Unfortunately, the discussion around #119 happened during a call that we don't have meeting minutes for. The consensus there was that something like DMZ is required. We then worked through the above proposal together. Did we just have completely different understandings of what we were putting a proposal together that never reared its head during 2 hours of discussion lol?

I'm not married or committed to the necessity for DMZ at all. I really just want to know **how** an interface distinguishes between what's publicly accessible and what isn't. Let's just pretend DMZ doesn't exist at all and the following message arrives at Alice's hub: 

```json
{
  "descriptor": {
    "method": "CollectionsQuery",
    "schema": "https://schema.org/BlogPosting"
  }
}
```
how does the hub know whether Alice's blog posts are publicly available? notice that `authorization` is NOT present as a property in the message. What's the hub going to do?

> are we really going to create a system that requires all users and apps to add endless volumes of DMZ entries

'Endless volumes' seems a bit over-exaggerated don't you think? Very curious to know **how** a hub knows what's publicly accessible and what isn't

**Comment by csuwildcat** [comment]
@mistermoe the thinking was that anything not encrypted was something one could query for in Collections specifically, but but the same isn't true for Permissions, for instance. So for your example, you'd be able to get back all unencrypted BlogPosting objects when sending that query without authorization material. The flip side was that all objects that are encrypted were to be deemed de facto private and require authorization to release from any interface. It doesn't say this in the spec yet because we, as a group, need to decide on the final call/text.

**Comment by csuwildcat** [comment]
> and how is this different from authorization?

You don't have to authorize anyone to send you an email, they can just learn of your email address any number of in/out-of-band ways and send it. There are some interfaces in Hubs that behave that way, so this is about a settings type object that lets the user 'demilitarize' an interface method to allow even the possibility of passage beyond the hard block that deflects traffic.

**Comment by TallTed** [comment]
> With email, the burden of processing spam falls 100% on the recipient. With
email, I am not allowed to delegate spam filtering to an agent that dies
not also store the email. I’m stuck using Gmail. Please find a better
example.

@agropper -- There are multiple email service providers who will filter (probable) spam into `/dev/null` for you -- whether by acting as an agent, which typically uses your credentials, or by acting instead of Google to provide the various email account services under an address to which your Gmail address forwards, etc. -- but of course you must remember that false positives are then not recoverable nor even likely to be discoverable. Being "stuck using Gmail" or other service where "spam filtering [...] also [stores] the email" is a measure of your effort, not of what is available nor achievable.

**Comment by mistermoe** [comment]
> @mistermoe the thinking was that anything not encrypted was something one could query for in Collections specifically, but but the same isn't true for Permissions, for instance. So for your example, you'd be able to get back all unencrypted BlogPosting objects when sending that query without authorization material. The flip side was that all objects that are encrypted were to be deemed de facto private and require authorization to release from any interface. It doesn't say this in the spec yet because we, as a group, need to decide on the final call/text.

Thank you for clarifying. 

As mentioned previously, I think this puts people at a much higher risk of accidentally exposing data that they had no intention to make publicly available. It's far too indirect. privacy of one's data is then fully dependent on whether the capabilities used to write said data require that the data be encrypted. 

Since `PermissionsGrant` necessitates human intervention, we're relying upon  individuals being tech savvy and thorough enough to realize that a `PermissionsRequest` to write their tax returns to their hub should be granted with the caveat that the tax return be encrypted. If an individual doesn't realize that they've granted permission to write unencrypted tax returns, I guess those tax returns will be publicly available on query.

I don't have an alternative solution in mind. I thought that DMZ could be feasible but apparently the inevitable outcome is "endless volumes of DMZ policy entries".

Definitely let me know if i'm being too paranoid. My main goal with all of this was to ensure that there are sensible defaults in place that lean in favor of protecting people's privacy

**Comment by csuwildcat** [comment]
@mistermoe the other thing that can be done, if you're specifically worried about querying data that isn't encrypted, but desired to be kept private strictly in the sense of not being included in results, is to add a flag to objects that explicitly sets the object to `public: true`, which would default to 'keep this private' if not flagged on.

**Comment by decentralgabe** [comment]
Is this framing correct? If not, help me understand.

There are main three classes of data access:
1. **Public access**

This data is publicly indexable, meaning I may see you have a "DriversLicense" credential available, and anyone can access it.

2. **Permissioned access**

This data is publicly indexable, meaning I may see you have a "DriversLicense" credential available, but may not be able to access it.

To access it, I either need some correct combination of <method, schema> (what about authZ here?) _or_ a capability granting me access to the object. 

3. **Private access**

This data is not publicly indexable. I can access it...

a. Directly (e.g. you told me about your DriversLicense and I ask for it in my request, I will optionally need to present a capability or a <method, schema> tuple)
b. Indirectly (e.g. I present a capability or a <method, schema> tuple and get back some information)

**Comment by mistermoe** [comment]
@decentralgabe 

The adjustment that i would make to your framing is that there's no concept of seeing. There's no explicit way to see what "kind" of data exists within someone's hub without actually accessing the data itself. 

There are two main classes of data access when interfacing with a hub:
1. **Public Access**
This data requires no authZ / capabilities 

2. **Permissioned Access**
This data requires authZ / capabilities

**Comment by decentralgabe** [comment]
> @decentralgabe
> 
> The adjustment that i would make to your framing is that there's no concept of seeing. There's no explicit way to see what "kind" of data exists within someone's hub without actually accessing the data itself.
> 
> There are two main classes of data access when interfacing with a hub:
> 
> 1. **Public Access**
>    This data requires no authZ / capabilities
> 2. **Permissioned Access**
>    This data requires authZ / capabilities

Thanks for the clarification. With well-defined authZ / capabilities for <method, schema> pairs, is there still a need for a DMZ?

**Comment by mistermoe** [comment]
> @mistermoe the other thing that can be done, if you're specifically worried about querying data that isn't encrypted, but desired to be kept private strictly in the sense of not being included in results, is to add a flag to objects that explicitly sets the object to public: true, which would default to 'keep this private' if not flagged on.

🤷🏽  I'm tapped out. we can just go with all non-encrypted data being public by default for now and revisit this if needed after we've fleshed out authZ / capabilities. Additionally, if the purpose of DMZ is what you stated in [this comment](https://github.com/decentralized-identity/identity-hub/issues/125#issuecomment-1068644274) I see no need for DMZ being an explicit interface. 

The "policies" can be inferred by the existence of a single non-encrypted object for a given method/schema pairing (schema where relevant). This can basically be treated as an implementation optimization which would be outside the scope of the spec.

**Comment by csuwildcat** [comment]
@mistermoe I do fully agree that we can certainly proceed without it, and then reassess if we see Hubs getting hit with a bunch of spam that warrant providing a means of setting up blocks on things. We should enable the messages down to the interface with just ocap permissions to complete our work, because adding some fence like a DMZ isn't particularly hard to do later, if necessary.

**Comment by mistermoe** [comment]
Thanks for the discussion everyone. going to close this out
