### ISSUE TITLE
What are 'iss' and 'aud'?

### ISSUE THREAD

**Issue by llorllale** [decentralized-identity/identity-hub#45]
I keep seeing these two attributes in example requests but have found no definition for them thus far. In all examples, their values are DIDs... but DIDs belonging to what exactly?

**Comment by csuwildcat** [comment]
They are from the existing JWT/OIDC family of standards, and mean 'issuer' and 'audience', which generally map to the Issuing party and the Subject, in our use cases.

**Comment by llorllale** [comment]
@csuwildcat thank you
