### ISSUE TITLE
Source for specs?

### ISSUE THREAD

**Issue by llorllale** [decentralized-identity/identity-hub#46]
In terms of the definition of the spec, which has precedence:
1. [The explainer](https://github.com/decentralized-identity/identity-hub/blob/master/explainer.md), or
2. [hub-node-core](https://github.com/decentralized-identity/hub-node-core)

I ask because I saw that [this PR](https://github.com/decentralized-identity/hub-node-core/pull/13) was merged over the weekend, and it changes the object model. The identity-hub explainer has not been updated to reflect these changes.

**Comment by logangirvin** [comment]
We're working on updating the explainer to bring it in-line with hub-node-core. There is a spec linked within the hub-node-core PR to a document on the [revised request/response format](https://hackmd.io/_nmlmbh1SlKdr1TOPYmX_w?view#) as well as a branch for the [identity-hub explainer](https://github.com/decentralized-identity/identity-hub/blob/logangirvin/requestResponseUpdate/explainer.md) that still needs some review and revisions to additional areas like the permission and authorization docs before a pull request can be made.
