### ISSUE TITLE
Alias `@type` -> type

### ISSUE THREAD

**Issue by tplooker** [decentralized-identity/identity-hub#72]
`@type` is a JSON-LD keyword, however to better meet the expectations of JSON consumers of Identity Hub related data objects you can choose in how you define your JSON-LD context to alias the `@type` field as type which effectively means the JSON-LD syntax sugar would collapse into a single `@context` entry.

Example the following 

```
{
  "@context": "https://identity.foundation/schemas/hub",
  "@type": "FeatureDetectionRead"
}
```

Changes to

```
{
  "@context": "https://identity.foundation/schemas/hub",
  "type": "FeatureDetectionRead"
}
```

**Comment by bumblefudge** [comment]
Spec on aliasing:
https://json-ld.org/spec/latest/json-ld/#aliasing-keywords

I think carefully designing the context (and governing it over time in this group) would allow this kind of "JSON-friendlier" LD, if you can bake constraints into the spec via MUST statements about how to use it, how to inject defaults (and what those should be) for missing mandatory fields, etc. I'd recommend thinking through the issues around nested objects, what their id/@id can or needs be, etc. Cf also:

https://json-ld.org/spec/latest/json-ld/#scoped-contexts

**Comment by TallTed** [comment]
@bumblefudge -- Note that you should always code-wrap JSON keywords that start with `@`, such as `@id`, `@type`, or `@context`, as if you don't, Github pings the user with that handle, and they almost certainly aren't interested in your JSON-related commentary.

**Comment by bumblefudge** [comment]
🤦‍♀️ will `be better` next time, thanks for the tip!

**Comment by TallTed** [comment]
@bumblefudge -- I don't know what emoji you sent (still on macOS El Capitan; they may be rendered in future)... This is to suggest that you edit https://github.com/decentralized-identity/identity-hub/issues/72#issuecomment-863799202 to hold
```
their id/`@id` can
```
:-)   <== old skool ASCII emoticons always render ;-)

**Comment by bumblefudge** [comment]
`alt="woman-facepalming-emoji"`

original comment edited!

**Comment by csuwildcat** [comment]
Closing, as this Issue was covered in a recent PR: https://github.com/decentralized-identity/identity-hub/commit/d2a4633e33941cdec898d9ea3f93934837d857c0
