### ISSUE TITLE
Consider removal of Profile interface

### ISSUE THREAD

**Issue by mistermoe** [decentralized-identity/identity-hub#97]
i'm not suggesting that the _concept_ of Profile should be removed. Rather, basic profile information that describes the target DID entity could be exposed through the functionality provided by the `Collections`. Since the `Collections` interface provides a mechanism to store and retrieve data relative to shared schemas, it effectively provides a means to store and expose **profile** data in accordance to a given schema. The same outcome would be achieved with 1 less interface.

The main difference that comes to mind is that `Profile` interface messages do not require an `objectId` whereas `Collections` messages do. To me, this implies that there can only be **one** profile vs. **many** instances of the same collection (e.g. more than 1 `SocialMediaPosting`). This means that, if profile data was stored and retrieved by means of the `Collections` interface, there could be more than 1 profile. 

I'm curious as to what others think about this. Thanks in advance for taking the time to consider!

**Comment by csuwildcat** [comment]
@thehenrytsai Moe makes a good point, which I am neutral about. We should discuss this on the next WG call.

**Comment by mistermoe** [comment]
looks like this ended up happening based on these commits?

- https://github.com/decentralized-identity/identity-hub/commit/4137d334ef25f8cc13be44109202343b826f1aea
- https://github.com/decentralized-identity/identity-hub/commit/0bb15964cfc0bd20b2bf92ab7b339d1508413db6

**Comment by thehenrytsai** [comment]
Looks like it. The word "profile" doesn't exist in the entire spec now. Good to close.
